---
- name: Configure TightVNC Server
  hosts: all
  become: yes
  tasks:
    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - python3-pip
        - tightvncserver

    - name: Install pip pexpect
      pip:
        name: pexpect
        state: latest
  
    - name: Setup initial VNC server to set password
      expect:
        command: tightvncserver :2
        responses:
          Password: "YourVNCpassword"
          Verify: "YourVNCpassword"
          "Would you like to enter a view-only password (y/n)?": "n"
      ignore_errors: yes

    - name: Kill any existing VNC server sessions
      shell: tightvncserver -kill :2
      ignore_errors: yes

    - name: Create VNC server script
      copy:
        dest: /usr/local/bin/vncserver
        mode: '0755'
        content: |
          #!/bin/bash
          PATH="$PATH:/usr/bin/"
          DISPLAY="2"
          DEPTH="24"
          GEOMETRY="1280x1024"
          OPTIONS="-depth ${DEPTH} -geometry ${GEOMETRY} :${DISPLAY}"

          case "$1" in
          start)
            /usr/bin/tightvncserver ${OPTIONS}
            ;;

          stop)
            /usr/bin/tightvncserver -kill :${DISPLAY}
            ;;

          restart)
            $0 stop
            $0 start
            ;;
          esac
          exit 0

    - name: Create systemd service for VNC server
      copy:
        dest: /etc/systemd/system/vncserver.service
        mode: '0644'
        content: |
          [Unit]
          Description=TightVNC Service Unit

          [Service]
          Type=forking
          ExecStart=/usr/local/bin/vncserver start
          ExecStop=/usr/local/bin/vncserver stop
          ExecReload=/usr/local/bin/vncserver restart
          User=root

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon and enable & start VNC service
      systemd:
        daemon_reload: yes
        name: vncserver.service
        enabled: yes
        state: started
