- hosts: all
  become: yes
  tasks:
    - name: Installation des paquets nécessaires pour VNC et GNOME
      apt:
        name:
          - python3-pip
          - gnome-core
          - task-gnome-desktop
          - tightvncserver
          - xfonts-base
        state: present
        update_cache: yes

    - name: Install pip pexpect
      pip:
        name: pexpect
        state: latest

    - name: Définition du mot de passe VNC
      expect:
        command: "tightvncserver :2"
        responses:
          (?i)password: "votre_mot_de_passe"
          (?i)verify: "votre_mot_de_passe"
      no_log: false
      become_user: "{{ ansible_env.USER }}"
    
    - name: kill le serveur VNC
      command: "tightvncserver -kill :2"
      become_user: "{{ ansible_env.USER }}"

    - name: Configuration du démarrage automatique du serveur VNC
      blockinfile:
        path: "/home/{{ ansible_env.USER }}/.vnc/xstartup"
        create: yes
        block: |
          #!/bin/bash
          xrdb $HOME/.Xresources
          startxfce4 &

    - name: Assurer que le script xstartup est exécutable
      file:
        path: "/home/{{ ansible_env.USER }}/.vnc/xstartup"
        mode: 0755

    - name: Installation et configuration d'un service systemd pour VNC
      blockinfile:
        path: "/etc/systemd/system/vncserver@.service"
        create: yes
        block: |
          [Unit]
          Description=Start TightVNC server at startup
          After=syslog.target network.target

          [Service]
          Type=forking
          User={{ ansible_env.USER }}
          PAMName=login
          PIDFile=/home/{{ ansible_env.USER }}/.vnc/%H:%i.pid
          ExecStartPre=-/usr/bin/vncserver -kill :%i > /dev/null 2>&1
          ExecStart=/usr/bin/vncserver -depth 24 -geometry 1280x800 :%i
          ExecStop=/usr/bin/vncserver -kill :%i

          [Install]
          WantedBy=multi-user.target

    - name: Activer et démarrer le service VNC
      systemd:
        name: vncserver@2
        enabled: yes
        state: started

1- installer tightvncserver
2- en tant que root: executer tightvncserver et gere les input (Password: 
Verify:   
Would you like to enter a view-only password (y/n)? n
)
3- en tant que root: executer tightvncserver -kill :2
4- cree un script dans /usr/local/bin/vncserver ->
#!/bin/bash
PATH="$PATH:/usr/bin/"
DISPLAY="2"
DEPTH="24"
GEOMETRY="1280x1204"
OPTIONS="-depth ${DEPTH} -geometry ${GEOMETRY} :${DISPLAY}"

case "$1" in
start)
/usr/bin/tightvncserver ${OPTIONS}
;;

stop)
/usr/bin/tightvncserver -kill :${DISPLAY}
;;

restart)
$0 stop
$0 start
;;
esac
exit 0
5- rendre le script executable
6- creer un service systemd pour le script ->
[Unit]
Description=TigthVNC Service Unit

[Service]
Type=forking
ExecStart=/usr/local/bin/vncserver start
ExecStop=/usr/local/bin/vncserver stop
ExecReload=/usr/local/bin/vncserver restart
User=root

[Install]
WantedBy=multi-user.target
7- activer et demarrer le service
systemctl daemon-reload
systemctl enable vncserver.service
systemctl start vncserver.service