---
- hosts: localhost
  become: yes
  tasks:
    - name: Create Prometheus user
      user:
        name: prometheus
        system: yes
        shell: /bin/false

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      with_items:
        - /etc/prometheus
        - /var/lib/prometheus
        - /etc/prometheus/consoles
        - /etc/prometheus/console_libraries

    - name: Copy Prometheus configuration file
      copy:
        src: files/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Install Prometheus dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - wget
        - tar

    - name: Download and extract Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.33.1/prometheus-2.33.1.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Create Prometheus user
      user:
        name: prometheus
        system: yes
        shell: /bin/false

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
      with_items:
        - /etc/prometheus
        - /var/lib/prometheus
        - /etc/prometheus/consoles
        - /etc/prometheus/console_libraries

    - name: Copy Prometheus systemd service file
      copy:
        src: files/prometheus.service
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd to recognize new Prometheus service
      systemd:
        daemon_reload: yes

    - name: Enable and start Prometheus service
      systemd:
        name: prometheus
        enabled: yes
        state: started

    - name: Restart Prometheus service
      service:
        name: prometheus
        state: restarted
