---
- hosts: localhost
  become: yes
  tasks:
    - name: Install Pip
      apt:
        name: python3-pip
        state: latest

    - name: Install pip pexpect
      pip:
        name: pexpect
        state: latest

    - name: Install TightVNC Server
      apt:
        name: tightvncserver
        state: latest

    - name: Set VNC password
      expect:
        command: tightvncpasswd
        responses:
          (?i)password: "{{ vnc_password }}"
          (?i)verify: "{{ vnc_password }}"
          (?i)Would you like to enter a view-only password \(y/n\)\? "n"
        echo: no
      vars:
        vnc_password: "password"
      no_log: true


    - name: Install Websockify
      apt:
        name: websockify
        state: latest

    - name: Copy Websockify systemd service file
      copy:
        src: files/websockify.service
        dest: /etc/systemd/system/websockify.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd to recognize new Prometheus service
      systemd:
        daemon_reload: yes

    - name: Enable and start Websockify service
      systemd:
        name: websockify
        enabled: yes
        state: started