#!/bin/bash
PATH="$PATH:/usr/bin/"
DISPLAY="2"
DEPTH="24"
GEOMETRY="1280x1024"
OPTIONS="-depth ${DEPTH} -geometry ${GEOMETRY} :${DISPLAY}"

case "$1" in
start)
/usr/bin/tightvncserver ${OPTIONS}
;;

stop)
/usr/bin/tightvncserver -kill :${DISPLAY}
;;

restart)
$0 stop
$0 start
;;
esac
exit 0